### PR TITLE
Rails3

### PR DESCRIPTION
**Pull request by obrok**
Rubytime migrated to Rails 3. Requires Ruby 1.9.2. Most things work. Authentication done with devise. Some issues remain, most notably date formats and css for devise. I tried to leave as much of the original structure intact as possible at least until I had the app running so there are definitely places which could be DRYed up but that's for later.

I'm creating a pull request more for the puropse of comments then to actually merge it at this point.

### CODE REVIEW

**Comment by arthwood** [comment]
@mackuba Your "some more improvements" could save this PR 😄 🕐

**Comment by obrok** [comment]
:D

**Comment by mackuba** [comment]
😅

**Comment by mariusz** [comment]
@mackuba making the biggest `FIXME` in Lunar Logic history.

**Pull request closed without merging**
